# Generated by Django 5.0 on 2024-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='foodimage/'),
        ),
    ]
