# Generated by Django 5.0 on 2024-02-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0004_dailycalory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycalory',
            name='dtype',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
