# Generated by Django 5.0 on 2024-02-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0008_alter_foodmodel_foodimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycalory',
            name='dfoodimg',
        ),
    ]
