# Generated by Django 5.0 on 2024-02-12 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0009_remove_dailycalory_dfoodimg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='fav',
            field=models.ManyToManyField(blank=True, default=False, related_name='favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
