# Generated by Django 5.0 on 2024-02-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0012_alter_register_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='user_register',
        ),
    ]
