# Generated by Django 5.0.7 on 2024-07-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0014_delete_user_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycalory',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='dailycalory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
