# Generated by Django 5.0.7 on 2024-07-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0015_alter_dailycalory_options_dailycalory_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycalory',
            options={},
        ),
    ]
